/* Generated by BOLTS, do not modify */
/* Copyright by: Johannes Reinhardt <jreinhardt@ist-dein-freund.de> */
/* CC-BY-SA <http://creativecommons.org/licenses/by-sa/3.0/> */
function DIN933_table_0(key) = 
//d1, k, s
key == "M2.5" ? [2.5, 1.7, 5.0] : 
key == "M39" ? [39.0, 25.0, 60.0] : 
key == "M52" ? [52.0, 33.0, 80.0] : 
key == "M36" ? [36.0, 22.5, 55.0] : 
key == "M33" ? [33.0, 21.0, 50.0] : 
key == "M30" ? [30.0, 18.7, 46.0] : 
key == "M5" ? [5.0, 3.5, 8.0] : 
key == "M4" ? [4.0, 2.8, 7.0] : 
key == "M7" ? [7.0, 4.8, 11.0] : 
key == "M6" ? [6.0, 4.0, 10.0] : 
key == "M3" ? [3.0, 2.0, 5.5] : 
key == "M2" ? [2.0, 1.4, 4.0] : 
key == "M8" ? [8.0, 5.3, 13.0] : 
key == "M3.5" ? [3.5, 2.4, 6.0] : 
key == "M24" ? [24.0, 15.0, 36.0] : 
key == "M48" ? [48.0, 30.0, 75.0] : 
key == "M64" ? [64.0, 40.0, 95.0] : 
key == "M42" ? [42.0, 26.0, 65.0] : 
key == "M27" ? [27.0, 17.0, 41.0] : 
key == "M20" ? [20.0, 12.5, 30.0] : 
key == "M22" ? [22.0, 14.0, 32.0] : 
key == "M45" ? [45.0, 28.0, 70.0] : 
key == "M10" ? [10.0, 6.4, 17.0] : 
key == "M12" ? [12.0, 7.5, 19.0] : 
key == "M14" ? [14.0, 8.8, 22.0] : 
key == "M1.6" ? [1.6, 1.1, 3.2] : 
key == "M16" ? [16.0, 10.0, 24.0] : 
key == "M18" ? [18.0, 11.5, 27.0] : 
"Error";

/* Generated by BOLTS, do not modify */
/* Copyright by: Johannes Reinhardt <jreinhardt@ist-dein-freund.de> */
/* CC-BY-SA <http://creativecommons.org/licenses/by-sa/3.0/> */
function DIN933_table_1(key) = 
//e, h
key == "M2.5" ? [5.45, "None"] : 
key == "M39" ? [66.44, "None"] : 
key == "M52" ? [88.25, "None"] : 
key == "M36" ? [60.79, 12.0] : 
key == "M33" ? [55.37, 10.5] : 
key == "M30" ? [50.85, 10.5] : 
key == "M5" ? [8.79, 2.4] : 
key == "M4" ? [7.66, 2.1] : 
key == "M7" ? [12.12, "None"] : 
key == "M6" ? [11.05, 3.0] : 
key == "M3" ? [6.01, 1.5] : 
key == "M2" ? [4.32, "None"] : 
key == "M8" ? [14.38, 3.75] : 
key == "M3.5" ? [6.58, "None"] : 
key == "M24" ? [39.98, 9.0] : 
key == "M48" ? [82.6, "None"] : 
key == "M64" ? [104.86, "None"] : 
key == "M42" ? [71.3, "None"] : 
key == "M27" ? [45.2, 9.0] : 
key == "M20" ? [33.53, 7.5] : 
key == "M22" ? [35.72, 7.5] : 
key == "M45" ? [76.95, "None"] : 
key == "M10" ? [18.9, 4.5] : 
key == "M12" ? [21.1, 5.25] : 
key == "M14" ? [24.49, 6.0] : 
key == "M1.6" ? [3.48, "None"] : 
key == "M16" ? [26.75, 6.0] : 
key == "M18" ? [30.14, 7.5] : 
"Error";

